/* ex: set ro ft=c: -*- buffer-read-only: t -*-
 *
 *    opnames.h
 *
 *    Copyright (C) 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
 *    2008 by Larry Wall and others
 *
 *    You may distribute under the terms of either the GNU General Public
 *    License or the Artistic License, as specified in the README file.
 *
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is built by regen/opcode.pl from its data.
 * Any changes made here will be lost!
 */

typedef enum opcode {
	OP_NULL		 = 0,
	OP_STUB		 = 1,
	OP_SCALAR	 = 2,
	OP_PUSHMARK	 = 3,
	OP_WANTARRAY	 = 4,
	OP_CONST	 = 5,
	OP_GVSV		 = 6,
	OP_GV		 = 7,
	OP_GELEM	 = 8,
	OP_PADSV	 = 9,
	OP_PADAV	 = 10,
	OP_PADHV	 = 11,
	OP_PADANY	 = 12,
	OP_SASSIGN	 = 13,
	OP_AASSIGN	 = 14,
	OP_CHOP		 = 15,
	OP_SCHOP	 = 16,
	OP_CHOMP	 = 17,
	OP_SCHOMP	 = 18,
	OP_DEFINED	 = 19,
	OP_UNDEF	 = 20,
	OP_STUDY	 = 21,
	OP_POS		 = 22,
	OP_PREINC	 = 23,
	OP_I_PREINC	 = 24,
	OP_PREDEC	 = 25,
	OP_I_PREDEC	 = 26,
	OP_POSTINC	 = 27,
	OP_I_POSTINC	 = 28,
	OP_POSTDEC	 = 29,
	OP_I_POSTDEC	 = 30,
	OP_MULTIPLY	 = 31,
	OP_I_MULTIPLY	 = 32,
	OP_U_MULTIPLY	 = 33,
	OP_DIVIDE	 = 34,
	OP_I_DIVIDE	 = 35,
	OP_MODULO	 = 36,
	OP_I_MODULO	 = 37,
	OP_REPEAT	 = 38,
	OP_ADD		 = 39,
	OP_I_ADD	 = 40,
	OP_U_ADD	 = 41,
	OP_SUBTRACT	 = 42,
	OP_I_SUBTRACT	 = 43,
	OP_U_SUBTRACT	 = 44,
	OP_CONCAT	 = 45,
	OP_STRINGIFY	 = 46,
	OP_POW		 = 47,
	OP_I_POW	 = 48,
	OP_LEFT_SHIFT	 = 49,
	OP_RIGHT_SHIFT	 = 50,
	OP_LT		 = 51,
	OP_I_LT		 = 52,
	OP_GT		 = 53,
	OP_I_GT		 = 54,
	OP_LE		 = 55,
	OP_I_LE		 = 56,
	OP_GE		 = 57,
	OP_I_GE		 = 58,
	OP_EQ		 = 59,
	OP_I_EQ		 = 60,
	OP_NE		 = 61,
	OP_I_NE		 = 62,
	OP_CMP		 = 63,
	OP_I_CMP	 = 64,
	OP_S_LT		 = 65,
	OP_S_GT		 = 66,
	OP_S_LE		 = 67,
	OP_S_GE		 = 68,
	OP_S_EQ		 = 69,
	OP_S_NE		 = 70,
	OP_S_CMP	 = 71,
	OP_BIT_AND	 = 72,
	OP_BIT_XOR	 = 73,
	OP_BIT_OR	 = 74,
	OP_I_BIT_AND	 = 75,
	OP_I_BIT_XOR	 = 76,
	OP_I_BIT_OR	 = 77,
	OP_S_BIT_AND	 = 78,
	OP_S_BIT_XOR	 = 79,
	OP_S_BIT_OR	 = 80,
	OP_NEGATE	 = 81,
	OP_I_NEGATE	 = 82,
	OP_NOT		 = 83,
	OP_COMPLEMENT	 = 84,
	OP_I_COMPLEMENT	 = 85,
	OP_S_COMPLEMENT	 = 86,
	OP_SMARTMATCH	 = 87,
	OP_ATAN2	 = 88,
	OP_SIN		 = 89,
	OP_COS		 = 90,
	OP_RAND		 = 91,
	OP_SRAND	 = 92,
	OP_EXP		 = 93,
	OP_LOG		 = 94,
	OP_SQRT		 = 95,
	OP_INT		 = 96,
	OP_HEX		 = 97,
	OP_OCT		 = 98,
	OP_ABS		 = 99,
	OP_INT_CONST	 = 100,
	OP_UINT_CONST	 = 101,
	OP_STR_CONST	 = 102,
	OP_NUM_CONST	 = 103,
	OP_BOX_INT	 = 104,
	OP_BOX_UINT	 = 105,
	OP_BOX_STR	 = 106,
	OP_BOX_NUM	 = 107,
	OP_UNBOX_INT	 = 108,
	OP_UNBOX_UINT	 = 109,
	OP_UNBOX_STR	 = 110,
	OP_UNBOX_NUM	 = 111,
	OP_INT_SASSIGN	 = 112,
	OP_UINT_SASSIGN	 = 113,
	OP_NUM_SASSIGN	 = 114,
	OP_STR_SASSIGN	 = 115,
	OP_INT_PADSV	 = 116,
	OP_UINT_PADSV	 = 117,
	OP_STR_PADSV	 = 118,
	OP_NUM_PADSV	 = 119,
	OP_UINT_LEFT_SHIFT = 120,
	OP_UINT_RIGHT_SHIFT = 121,
	OP_UINT_POW	 = 122,
	OP_UINT_COMPLEMENT = 123,
	OP_INT_PREINC	 = 124,
	OP_INT_PREDEC	 = 125,
	OP_INT_POSTINC	 = 126,
	OP_INT_POSTDEC	 = 127,
	OP_INT_ADD	 = 128,
	OP_INT_SUBTRACT	 = 129,
	OP_INT_MULTIPLY	 = 130,
	OP_INT_DIVIDE	 = 131,
	OP_INT_MODULO	 = 132,
	OP_INT_NEGATE	 = 133,
	OP_INT_NOT	 = 134,
	OP_INT_ABS	 = 135,
	OP_INT_LT	 = 136,
	OP_INT_GT	 = 137,
	OP_INT_LE	 = 138,
	OP_INT_GE	 = 139,
	OP_INT_EQ	 = 140,
	OP_INT_NE	 = 141,
	OP_NUM_ADD	 = 142,
	OP_NUM_SUBTRACT	 = 143,
	OP_NUM_MULTIPLY	 = 144,
	OP_NUM_DIVIDE	 = 145,
	OP_NUM_ATAN2	 = 146,
	OP_NUM_POW	 = 147,
	OP_NUM_SIN	 = 148,
	OP_NUM_COS	 = 149,
	OP_NUM_EXP	 = 150,
	OP_NUM_LOG	 = 151,
	OP_NUM_SQRT	 = 152,
	OP_RV2GV	 = 153,
	OP_RV2SV	 = 154,
	OP_AV2ARYLEN	 = 155,
	OP_RV2CV	 = 156,
	OP_ANONCODE	 = 157,
	OP_PROTOTYPE	 = 158,
	OP_REFGEN	 = 159,
	OP_SREFGEN	 = 160,
	OP_REF		 = 161,
	OP_BLESS	 = 162,
	OP_BACKTICK	 = 163,
	OP_GLOB		 = 164,
	OP_READLINE	 = 165,
	OP_RCATLINE	 = 166,
	OP_REGCMAYBE	 = 167,
	OP_REGCRESET	 = 168,
	OP_REGCOMP	 = 169,
	OP_MATCH	 = 170,
	OP_QR		 = 171,
	OP_SUBST	 = 172,
	OP_SUBSTCONT	 = 173,
	OP_TRANS	 = 174,
	OP_TRANSR	 = 175,
	OP_LENGTH	 = 176,
	OP_SUBSTR	 = 177,
	OP_VEC		 = 178,
	OP_INDEX	 = 179,
	OP_RINDEX	 = 180,
	OP_SPRINTF	 = 181,
	OP_FORMLINE	 = 182,
	OP_ORD		 = 183,
	OP_CHR		 = 184,
	OP_CRYPT	 = 185,
	OP_UCFIRST	 = 186,
	OP_LCFIRST	 = 187,
	OP_UC		 = 188,
	OP_LC		 = 189,
	OP_QUOTEMETA	 = 190,
	OP_RV2AV	 = 191,
	OP_AELEMFAST	 = 192,
	OP_AELEMFAST_LEX = 193,
	OP_AELEM	 = 194,
	OP_I_AELEM	 = 195,
	OP_N_AELEM	 = 196,
	OP_S_AELEM	 = 197,
	OP_AELEMFAST_LEX_U = 198,
	OP_AELEM_U	 = 199,
	OP_I_AELEM_U	 = 200,
	OP_N_AELEM_U	 = 201,
	OP_S_AELEM_U	 = 202,
	OP_INT_AELEM	 = 203,
	OP_NUM_AELEM	 = 204,
	OP_STR_AELEM	 = 205,
	OP_INT_AELEM_U	 = 206,
	OP_NUM_AELEM_U	 = 207,
	OP_STR_AELEM_U	 = 208,
	OP_ASLICE	 = 209,
	OP_KVASLICE	 = 210,
	OP_AEACH	 = 211,
	OP_AVALUES	 = 212,
	OP_AKEYS	 = 213,
	OP_EACH		 = 214,
	OP_VALUES	 = 215,
	OP_KEYS		 = 216,
	OP_DELETE	 = 217,
	OP_EXISTS	 = 218,
	OP_RV2HV	 = 219,
	OP_HELEM	 = 220,
	OP_HSLICE	 = 221,
	OP_KVHSLICE	 = 222,
	OP_MULTIDEREF	 = 223,
	OP_UNPACK	 = 224,
	OP_PACK		 = 225,
	OP_SPLIT	 = 226,
	OP_JOIN		 = 227,
	OP_LIST		 = 228,
	OP_LSLICE	 = 229,
	OP_ANONLIST	 = 230,
	OP_ANONHASH	 = 231,
	OP_SPLICE	 = 232,
	OP_PUSH		 = 233,
	OP_POP		 = 234,
	OP_SHIFT	 = 235,
	OP_UNSHIFT	 = 236,
	OP_SORT		 = 237,
	OP_REVERSE	 = 238,
	OP_GREPSTART	 = 239,
	OP_GREPWHILE	 = 240,
	OP_MAPSTART	 = 241,
	OP_MAPWHILE	 = 242,
	OP_RANGE	 = 243,
	OP_FLIP		 = 244,
	OP_FLOP		 = 245,
	OP_AND		 = 246,
	OP_OR		 = 247,
	OP_XOR		 = 248,
	OP_DOR		 = 249,
	OP_COND_EXPR	 = 250,
	OP_ANDASSIGN	 = 251,
	OP_ORASSIGN	 = 252,
	OP_DORASSIGN	 = 253,
	OP_METHOD	 = 254,
	OP_ENTERSUB	 = 255,
	OP_ENTERXSSUB	 = 256,
	OP_LEAVESUB	 = 257,
	OP_LEAVESUBLV	 = 258,
	OP_SIGNATURE	 = 259,
	OP_CALLER	 = 260,
	OP_WARN		 = 261,
	OP_DIE		 = 262,
	OP_RESET	 = 263,
	OP_LINESEQ	 = 264,
	OP_NEXTSTATE	 = 265,
	OP_DBSTATE	 = 266,
	OP_UNSTACK	 = 267,
	OP_ENTER	 = 268,
	OP_LEAVE	 = 269,
	OP_SCOPE	 = 270,
	OP_ENTERITER	 = 271,
	OP_ITER		 = 272,
	OP_ITER_ARY	 = 273,
	OP_ITER_LAZYIV	 = 274,
	OP_ENTERLOOP	 = 275,
	OP_LEAVELOOP	 = 276,
	OP_RETURN	 = 277,
	OP_LAST		 = 278,
	OP_NEXT		 = 279,
	OP_REDO		 = 280,
	OP_DUMP		 = 281,
	OP_GOTO		 = 282,
	OP_EXIT		 = 283,
	OP_METHOD_NAMED	 = 284,
	OP_METHOD_SUPER	 = 285,
	OP_METHOD_REDIR	 = 286,
	OP_METHOD_REDIR_SUPER = 287,
	OP_ENTERGIVEN	 = 288,
	OP_LEAVEGIVEN	 = 289,
	OP_ENTERWHEN	 = 290,
	OP_LEAVEWHEN	 = 291,
	OP_BREAK	 = 292,
	OP_CONTINUE	 = 293,
	OP_OPEN		 = 294,
	OP_CLOSE	 = 295,
	OP_PIPE_OP	 = 296,
	OP_FILENO	 = 297,
	OP_UMASK	 = 298,
	OP_BINMODE	 = 299,
	OP_TIE		 = 300,
	OP_UNTIE	 = 301,
	OP_TIED		 = 302,
	OP_DBMOPEN	 = 303,
	OP_DBMCLOSE	 = 304,
	OP_SSELECT	 = 305,
	OP_SELECT	 = 306,
	OP_GETC		 = 307,
	OP_READ		 = 308,
	OP_ENTERWRITE	 = 309,
	OP_LEAVEWRITE	 = 310,
	OP_PRTF		 = 311,
	OP_PRINT	 = 312,
	OP_SAY		 = 313,
	OP_SYSOPEN	 = 314,
	OP_SYSSEEK	 = 315,
	OP_SYSREAD	 = 316,
	OP_SYSWRITE	 = 317,
	OP_EOF		 = 318,
	OP_TELL		 = 319,
	OP_SEEK		 = 320,
	OP_TRUNCATE	 = 321,
	OP_FCNTL	 = 322,
	OP_IOCTL	 = 323,
	OP_FLOCK	 = 324,
	OP_SEND		 = 325,
	OP_RECV		 = 326,
	OP_SOCKET	 = 327,
	OP_SOCKPAIR	 = 328,
	OP_BIND		 = 329,
	OP_CONNECT	 = 330,
	OP_LISTEN	 = 331,
	OP_ACCEPT	 = 332,
	OP_SHUTDOWN	 = 333,
	OP_GSOCKOPT	 = 334,
	OP_SSOCKOPT	 = 335,
	OP_GETSOCKNAME	 = 336,
	OP_GETPEERNAME	 = 337,
	OP_LSTAT	 = 338,
	OP_STAT		 = 339,
	OP_FTRREAD	 = 340,
	OP_FTRWRITE	 = 341,
	OP_FTREXEC	 = 342,
	OP_FTEREAD	 = 343,
	OP_FTEWRITE	 = 344,
	OP_FTEEXEC	 = 345,
	OP_FTIS		 = 346,
	OP_FTSIZE	 = 347,
	OP_FTMTIME	 = 348,
	OP_FTATIME	 = 349,
	OP_FTCTIME	 = 350,
	OP_FTROWNED	 = 351,
	OP_FTEOWNED	 = 352,
	OP_FTZERO	 = 353,
	OP_FTSOCK	 = 354,
	OP_FTCHR	 = 355,
	OP_FTBLK	 = 356,
	OP_FTFILE	 = 357,
	OP_FTDIR	 = 358,
	OP_FTPIPE	 = 359,
	OP_FTSUID	 = 360,
	OP_FTSGID	 = 361,
	OP_FTSVTX	 = 362,
	OP_FTLINK	 = 363,
	OP_FTTTY	 = 364,
	OP_FTTEXT	 = 365,
	OP_FTBINARY	 = 366,
	OP_CHDIR	 = 367,
	OP_CHOWN	 = 368,
	OP_CHROOT	 = 369,
	OP_UNLINK	 = 370,
	OP_CHMOD	 = 371,
	OP_UTIME	 = 372,
	OP_RENAME	 = 373,
	OP_LINK		 = 374,
	OP_SYMLINK	 = 375,
	OP_READLINK	 = 376,
	OP_MKDIR	 = 377,
	OP_RMDIR	 = 378,
	OP_OPEN_DIR	 = 379,
	OP_READDIR	 = 380,
	OP_TELLDIR	 = 381,
	OP_SEEKDIR	 = 382,
	OP_REWINDDIR	 = 383,
	OP_CLOSEDIR	 = 384,
	OP_FORK		 = 385,
	OP_WAIT		 = 386,
	OP_WAITPID	 = 387,
	OP_SYSTEM	 = 388,
	OP_EXEC		 = 389,
	OP_KILL		 = 390,
	OP_GETPPID	 = 391,
	OP_GETPGRP	 = 392,
	OP_SETPGRP	 = 393,
	OP_GETPRIORITY	 = 394,
	OP_SETPRIORITY	 = 395,
	OP_TIME		 = 396,
	OP_TMS		 = 397,
	OP_LOCALTIME	 = 398,
	OP_GMTIME	 = 399,
	OP_ALARM	 = 400,
	OP_SLEEP	 = 401,
	OP_SHMGET	 = 402,
	OP_SHMCTL	 = 403,
	OP_SHMREAD	 = 404,
	OP_SHMWRITE	 = 405,
	OP_MSGGET	 = 406,
	OP_MSGCTL	 = 407,
	OP_MSGSND	 = 408,
	OP_MSGRCV	 = 409,
	OP_SEMOP	 = 410,
	OP_SEMGET	 = 411,
	OP_SEMCTL	 = 412,
	OP_REQUIRE	 = 413,
	OP_DOFILE	 = 414,
	OP_HINTSEVAL	 = 415,
	OP_ENTEREVAL	 = 416,
	OP_LEAVEEVAL	 = 417,
	OP_ENTERTRY	 = 418,
	OP_LEAVETRY	 = 419,
	OP_GHBYNAME	 = 420,
	OP_GHBYADDR	 = 421,
	OP_GHOSTENT	 = 422,
	OP_GNBYNAME	 = 423,
	OP_GNBYADDR	 = 424,
	OP_GNETENT	 = 425,
	OP_GPBYNAME	 = 426,
	OP_GPBYNUMBER	 = 427,
	OP_GPROTOENT	 = 428,
	OP_GSBYNAME	 = 429,
	OP_GSBYPORT	 = 430,
	OP_GSERVENT	 = 431,
	OP_SHOSTENT	 = 432,
	OP_SNETENT	 = 433,
	OP_SPROTOENT	 = 434,
	OP_SSERVENT	 = 435,
	OP_EHOSTENT	 = 436,
	OP_ENETENT	 = 437,
	OP_EPROTOENT	 = 438,
	OP_ESERVENT	 = 439,
	OP_GPWNAM	 = 440,
	OP_GPWUID	 = 441,
	OP_GPWENT	 = 442,
	OP_SPWENT	 = 443,
	OP_EPWENT	 = 444,
	OP_GGRNAM	 = 445,
	OP_GGRGID	 = 446,
	OP_GGRENT	 = 447,
	OP_SGRENT	 = 448,
	OP_EGRENT	 = 449,
	OP_GETLOGIN	 = 450,
	OP_SYSCALL	 = 451,
	OP_LOCK		 = 452,
	OP_ONCE		 = 453,
	OP_CUSTOM	 = 454,
	OP_COREARGS	 = 455,
	OP_AVHVSWITCH	 = 456,
	OP_RUNCV	 = 457,
	OP_FC		 = 458,
	OP_PADCV	 = 459,
	OP_INTROCV	 = 460,
	OP_CLONECV	 = 461,
	OP_PADRANGE	 = 462,
	OP_REFASSIGN	 = 463,
	OP_LVREF	 = 464,
	OP_LVREFSLICE	 = 465,
	OP_LVAVREF	 = 466,
	OP_ANONCONST	 = 467,
	OP_max		
} opcode;

#define MAXO 468
#define OP_FREED MAXO


/* core types */

typedef enum {
    type_none = 0,
    type_int = 1,
    type_uint = 2,
    type_num = 3,
    type_str = 4,
    type_Int = 5,
    type_UInt = 6,
    type_Num = 7,
    type_Str = 8,
    type_Bool = 9,
    type_Numeric = 10,
    type_Scalar = 11,
    type_Ref = 12,
    type_Sub = 13,
    type_Regexp = 14,
    type_Object = 15,
    type_Array = 16,
    type_Hash = 17,
    type_List = 18,
    type_Any = 19,
    type_Void = 255
} core_types_t;

#ifdef PERL_IN_OP_C
static const char* const
core_types_n[] = {
    "",
    "int",
    "uint",
    "num",
    "str",
    "Int",
    "UInt",
    "Num",
    "Str",
    "Bool",
    "Numeric",
    "Scalar",
    "Ref",
    "Sub",
    "Regexp",
    "Object",
    "Array",
    "Hash",
    "List",
    "Any",
    "Void",
};
#endif /* PERL_IN_OP_C */

/* PL_opargs encoding */

/* Lowest 10 bits of PL_opargs */
#define OA_MARK	1
#define OA_FOLDCONST	2
#define OA_RETSCALAR	4
#define OA_TARGET	8
#define OA_TARGLEX	24
#define OA_OTHERINT	32
#define OA_DANGEROUS	64
#define OA_DEFGV	128
#define OA_PURE	256
#define OA_BOXRET	512

/* The next 4 bits (10..13) encode op class information */
#define OCSHIFT 10

/* Each remaining 4bit nybbles of PL_opargs (i.e. bits 14..17, 18..21 etc)
 * encode the type for each arg */
#define OASHIFT 14

/* arg types */
#define OA_SCALAR  1
#define OA_LIST    2
#define OA_AVREF   3
#define OA_HVREF   4
#define OA_CVREF   5
#define OA_FILEREF 6
#define OA_SCALARREF 7
#define OA_OPTIONAL 8

/* 0b0011_1100_0000_0000 / 0xf000 */
#define OA_CLASS_MASK (0xf << OCSHIFT)

#define OA_BASEOP 	(0 << OCSHIFT)
#define OA_UNOP 	(1 << OCSHIFT)
#define OA_BINOP 	(2 << OCSHIFT)
#define OA_LOGOP 	(3 << OCSHIFT)
#define OA_LISTOP 	(4 << OCSHIFT)
#define OA_PMOP 	(5 << OCSHIFT)
#define OA_SVOP 	(6 << OCSHIFT)
#define OA_PADOP 	(7 << OCSHIFT)
#define OA_PVOP_OR_SVOP (8 << OCSHIFT)
#define OA_LOOP 	(9 << OCSHIFT)
#define OA_COP 		(10 << OCSHIFT)
#define OA_BASEOP_OR_UNOP (11 << OCSHIFT)
#define OA_FILESTATOP 	(12 << OCSHIFT)
#define OA_LOOPEXOP 	(13 << OCSHIFT)
#define OA_METHOP 	(14 << OCSHIFT)
#define OA_UNOP_AUX 	(15 << OCSHIFT)


#define OP_HAS_TARGLEX(ot) ((PL_opargs[ot] & OA_TARGLEX) == OA_TARGLEX)

#define OpCLASS(ot)      (PL_opargs[(ot)] & OA_CLASS_MASK)
#define OP_IS_BASEOP(ot) (OpCLASS(ot) == OA_BASEOP || OpCLASS(ot) == OA_BASEOP_OR_UNOP)
#define OP_IS_UNOP(ot)   (OpCLASS(ot) == OA_UNOP || OpCLASS(ot) == OA_BASEOP_OR_UNOP)
#define OP_IS_BINOP(ot)  OpCLASS(ot) == OA_BINOP
#define OP_IS_LOGOP(ot)  OpCLASS(ot) == OA_LOGOP
#define OP_IS_LISTOP(ot) OpCLASS(ot) == OA_LISTOP
#define OP_IS_PMOP(ot)   OpCLASS(ot) == OA_PMOP
#define OP_IS_SVOP(ot)   (OpCLASS(ot) == OA_SVOP || OpCLASS(ot) == OA_PVOP_OR_SVOP)
#define OP_IS_PADOP(ot)  OpCLASS(ot) == OA_PADOP
#define OP_IS_LOOP(ot)   OpCLASS(ot) == OA_LOOP
#define OP_IS_COP(ot)    OpCLASS(ot) == OA_COP
#define OP_IS_FILESTATOP(ot) OpCLASS(ot) == OA_FILESTATOP
#define OP_IS_METHOP(ot) OpCLASS(ot) == OA_METHOP

/* The other OP_IS_* macros are optimized to a simple range check because
   all the member OPs are contiguous in regen/opcodes table.
   regen/opcode.pl verifies the range contiguity, or generates an OR-equals
   expression */

#define OP_HAS_LIST(ot)	\
	((ot) == OP_AASSIGN || \
	 (ot) == OP_ANONHASH || \
	 (ot) == OP_ANONLIST || \
	 (ot) == OP_ASLICE || \
	 (ot) == OP_CHMOD || \
	 (ot) == OP_CHOMP || \
	 (ot) == OP_CHOP || \
	 (ot) == OP_CHOWN || \
	 (ot) == OP_DIE || \
	 (ot) == OP_ENTERSUB || \
	 (ot) == OP_ENTERXSSUB || \
	 (ot) == OP_EXEC || \
	 (ot) == OP_FORMLINE || \
	 (ot) == OP_GREPSTART || \
	 (ot) == OP_HSLICE || \
	 (ot) == OP_JOIN || \
	 (ot) == OP_KILL || \
	 (ot) == OP_KVASLICE || \
	 (ot) == OP_KVHSLICE || \
	 (ot) == OP_LIST || \
	 (ot) == OP_LSLICE || \
	 (ot) == OP_MAPSTART || \
	 (ot) == OP_OPEN || \
	 (ot) == OP_PACK || \
	 (ot) == OP_PRINT || \
	 (ot) == OP_PRTF || \
	 (ot) == OP_PUSH || \
	 (ot) == OP_REFGEN || \
	 (ot) == OP_REPEAT || \
	 (ot) == OP_RETURN || \
	 (ot) == OP_REVERSE || \
	 (ot) == OP_SAY || \
	 (ot) == OP_SORT || \
	 (ot) == OP_SPLICE || \
	 (ot) == OP_SPRINTF || \
	 (ot) == OP_SYSCALL || \
	 (ot) == OP_SYSTEM || \
	 (ot) == OP_TIE || \
	 (ot) == OP_UNLINK || \
	 (ot) == OP_UNSHIFT || \
	 (ot) == OP_UTIME || \
	 (ot) == OP_WARN)

#define OP_IS_SOCKET(ot)	\
	((ot) >= OP_SEND && (ot) <= OP_GETPEERNAME)

#define OP_IS_FILETEST(ot)	\
	((ot) >= OP_FTRREAD && (ot) <= OP_FTBINARY)

#define OP_IS_FILETEST_ACCESS(ot)	\
	((ot) >= OP_FTRREAD && (ot) <= OP_FTEEXEC)

#define OP_IS_NUMCOMPARE(ot)	\
	((ot) >= OP_LT && (ot) <= OP_I_CMP)

#define OP_IS_DIRHOP(ot)	\
	((ot) >= OP_READDIR && (ot) <= OP_CLOSEDIR)

#define OP_IS_INFIX_BIT(ot)	\
	((ot) >= OP_BIT_AND && (ot) <= OP_S_BIT_OR)

#define OP_IS_PADVAR(ot)	\
	((ot) >= OP_PADSV && (ot) <= OP_PADANY)

#define OP_IS_ITER(ot)	\
	((ot) >= OP_ITER && (ot) <= OP_ITER_LAZYIV)

/* backcompat old Perl 5 names: */
#if 1
#define OP_NCMP		 OP_CMP
#define OP_I_NCMP	 OP_I_CMP
#define OP_SLT		 OP_S_LT
#define OP_SGT		 OP_S_GT
#define OP_SLE		 OP_S_LE
#define OP_SGE		 OP_S_GE
#define OP_SEQ		 OP_S_EQ
#define OP_SNE		 OP_S_NE
#define OP_SCMP		 OP_S_CMP
#define OP_NBIT_AND	 OP_I_BIT_AND
#define OP_NBIT_XOR	 OP_I_BIT_XOR
#define OP_NBIT_OR	 OP_I_BIT_OR
#define OP_SBIT_AND	 OP_S_BIT_AND
#define OP_SBIT_XOR	 OP_S_BIT_XOR
#define OP_SBIT_OR	 OP_S_BIT_OR
#define OP_NCOMPLEMENT	 OP_I_COMPLEMENT
#define OP_SCOMPLEMENT	 OP_S_COMPLEMENT

#define Perl_pp_ncmp	 Perl_pp_cmp
#define Perl_pp_i_ncmp	 Perl_pp_i_cmp
#define Perl_pp_slt	 Perl_pp_s_lt
#define Perl_pp_sgt	 Perl_pp_s_gt
#define Perl_pp_sle	 Perl_pp_s_le
#define Perl_pp_sge	 Perl_pp_s_ge
#define Perl_pp_seq	 Perl_pp_s_eq
#define Perl_pp_sne	 Perl_pp_s_ne
#define Perl_pp_scmp	 Perl_pp_s_cmp
#define Perl_pp_nbit_and Perl_pp_i_bit_and
#define Perl_pp_nbit_xor Perl_pp_i_bit_xor
#define Perl_pp_nbit_or	 Perl_pp_i_bit_or
#define Perl_pp_sbit_and Perl_pp_s_bit_and
#define Perl_pp_sbit_xor Perl_pp_s_bit_xor
#define Perl_pp_sbit_or	 Perl_pp_s_bit_or
#define Perl_pp_ncomplement Perl_pp_i_complement
#define Perl_pp_scomplement Perl_pp_s_complement
#endif

/* ex: set ro: */
